version: 1
update_configs:
  - package_manager: 'dotnet:nuget'
    directory: '/'
    update_schedule: 'live'
    default_reviewers:
      - 'nogic1008'
    default_labels:
      - 'dependabot:robot:'
    commit_message:
      prefix: 'fix'
      prefix_development: 'chore'
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'security:patch'
